// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSW0MD1c1OksGpRJFdRMniOI4PCauzs5k',
    appId: '1:953957692494:web:1d96171eca9304ab24bf1f',
    messagingSenderId: '953957692494',
    projectId: 'instacart-33104',
    authDomain: 'instacart-33104.firebaseapp.com',
    storageBucket: 'instacart-33104.firebasestorage.app',
    measurementId: 'G-5JFFRKEE0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwaFWiOxz7TtKfcIALUab4g9QRePKer0',
    appId: '1:953957692494:android:a19ec074959211d724bf1f',
    messagingSenderId: '953957692494',
    projectId: 'instacart-33104',
    storageBucket: 'instacart-33104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGuUbite6PZ4AGEWkcf0o8sws4D9uR_OA',
    appId: '1:953957692494:ios:c79ed4fa516a0a5324bf1f',
    messagingSenderId: '953957692494',
    projectId: 'instacart-33104',
    storageBucket: 'instacart-33104.firebasestorage.app',
    iosBundleId: 'com.example.instacart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGuUbite6PZ4AGEWkcf0o8sws4D9uR_OA',
    appId: '1:953957692494:ios:c79ed4fa516a0a5324bf1f',
    messagingSenderId: '953957692494',
    projectId: 'instacart-33104',
    storageBucket: 'instacart-33104.firebasestorage.app',
    iosBundleId: 'com.example.instacart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSW0MD1c1OksGpRJFdRMniOI4PCauzs5k',
    appId: '1:953957692494:web:dd1e5d34f3ba673424bf1f',
    messagingSenderId: '953957692494',
    projectId: 'instacart-33104',
    authDomain: 'instacart-33104.firebaseapp.com',
    storageBucket: 'instacart-33104.firebasestorage.app',
    measurementId: 'G-2TMBX8JK78',
  );
}
